controller_list:
  - name: pos_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J
  - name: vel_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J
  - name: tor_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J
  - name: trajectory_follower
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - BJ
      - SJ
      - EJ
      - W1J
      - W2J
      - W3J