joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

joint1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_1
  pid: { p: 5, d: 10, i: 0.1, i_clamp: 200 }

joint2_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_2
  pid: { p: 170, d: 80, i: 0.1, i_clamp: 200 }

joint3_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_3
  pid: { p: 150, d: 30, i: 2, i_clamp: 200 }

joint4_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_4
  pid: { p: 1, d: 1, i: 2, i_clamp: 200 }

joint5_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_5
  pid: { p: 5, d: 1, i: 2, i_clamp: 200 }

joint6_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_6
  pid: { p: 0.1, d: 0.1, i: 0.1, i_clamp: 0.1 }
