robot2/joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1000

robot2/joint1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_1_heal2
  pid: { p: 5, d: 10, i: 0.1, i_clamp: 200 }

robot2/joint2_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_2_heal2
  pid: { p: 170, d: 80, i: 0.1, i_clamp: 200 }

robot2/joint3_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_3_heal2
  pid: { p: 150, d: 30, i: 2, i_clamp: 200 }

robot2/joint4_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_4_heal2
  pid: { p: 1, d: 1, i: 2, i_clamp: 200 }

robot2/joint5_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_5_heal2
  pid: { p: 5, d: 1, i: 2, i_clamp: 200 }

robot2/joint6_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: joint_6_heal2
  pid: { p: 0.1, d: 0.1, i: 0.1, i_clamp: 0.1 }
